mysite/articles/urls.py
from django.urls import path

from . import views
app_name = 'articles'

urlpatterns = [
    path('home', views.home, name='home'),
    path('stocks', views.stocks, name='stocks'),
    path('authors', views.authors, name='authors'),
    path('<uuid:article_uuid>/', views.article, name='article'),
    path('authors/<uuid:author_uuid>/', views.author, name='author'),

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
]

mysite/articles/models.py
from django.db import models
import uuid
from django.utils import timezone


class Tagtype(models.Model):
    slug = models.CharField(max_length=100,primary_key=True)
    name = models.CharField(max_length=100)

class Link(models.Model):
    content = models.URLField(max_length=200)
    linkself = models.URLField(max_length=200)

class ArticleLink(models.Model):
    articlelinkself = models.URLField(max_length=100)
    presentation = models.URLField(max_length=100)
    content_sequence = models.URLField(max_length=100)

class Pitch(models.Model):
    text = models.TextField()
    id = models.IntegerField(primary_key=True,editable=False)

class Image(models.Model):
    name = models.CharField(max_length=100)
    created = models.DateTimeField()
    url = models.URLField(max_length=100)
    image = models.URLField(max_length=100)
    modified = models.DateTimeField()
    featured = models.BooleanField(default=True)
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

class Instrument(models.Model):
    instrument_id = models.IntegerField(primary_key=True,editable=False)
    asset_class = models.CharField(max_length=100)
    exchange = models.CharField(max_length=100)
    symbol = models.CharField(max_length=100)
    primary = models.BooleanField(default=True)
    seo_name = models.CharField(max_length=100)
    company_name = models.CharField(max_length=100)
    syndicate = models.BooleanField(default=True)
    valid = models.BooleanField(default=True)
    links = models.OneToOneField(Link,on_delete=models.CASCADE)

class Author(models.Model):
    username = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    links = models.OneToOneField(Link,on_delete=models.CASCADE)
    fool_uid = models.IntegerField()
    primary = models.BooleanField(default=True)
    twitter_username = models.CharField(max_length=100,null=True, blank=True)
    small_avatar_url = models.CharField(max_length=100)
    long_bio = models.TextField(null=True, blank=True)
    first_name = models.CharField(max_length=100)
    byline = models.CharField(max_length=100)
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    contributor_type = models.CharField(max_length=100)
    large_avatar_url =  models.CharField(max_length=200)
    short_bio =  models.TextField()
    author_id = models.IntegerField()
    email = models.EmailField(max_length=100)

class Bureau(models.Model):
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    slug = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    links = models.OneToOneField(Link,on_delete=models.CASCADE)

class Collection(models.Model):
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    path = models.CharField(max_length=100)
    slug = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    links = models.OneToOneField(Link,on_delete=models.CASCADE)

class Tag(models.Model):
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    slug = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    tag_type = models.ManyToManyField(Tagtype)
    links = models.OneToOneField(Link,on_delete=models.CASCADE, null=True, blank=True)



class Article(models.Model):
    disclosure = models.TextField()
    promo = models.CharField(max_length=200)
    body = models.TextField()
    visibility = models.IntegerField(default=0) # not sure what this is
    article_type = models.CharField(max_length=100)
    publish_at = models.DateTimeField()
    path = models.CharField(max_length=100)
    static_page = models.BooleanField(default=False)
    author_override = models.CharField(max_length=100,null=True, blank=True) # not sure either
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created = models.DateTimeField()
    headline = models.CharField(max_length=100)
    modified = models.DateTimeField()
    product_id = models.IntegerField(default=0)
    video = models.CharField(max_length=100,null=True, blank=True)
    byline = models.CharField(max_length=100)
    insturments = models.ManyToManyField(Instrument)
    authors = models.ManyToManyField(Author, related_name='authors')
    bureau = models.ManyToManyField(Bureau)
    collection = models.ManyToManyField(Collection)
    tags = models.ManyToManyField(Tag)
    pitch = models.ManyToManyField(Pitch)
    links = models.OneToOneField(ArticleLink,null=True,on_delete=models.CASCADE)
    images = models.ManyToManyField(Image)

class Comment(models.Model):
    article = models.ForeignKey('Article',blank=True,null=True, on_delete=models.CASCADE, related_name='comments')
    body = models.TextField()
    name = models.CharField(max_length=100, null=True)
    created = models.DateTimeField(default=timezone.now)


class Quote(models.Model):
    company_name = models.CharField(max_length=100)
    symbol = models.CharField(max_length=100)
    exchange = models.CharField(max_length=100)
    exchange_name = models.CharField(max_length=100)
    isoalpha2countrycode = models.CharField(max_length=100)
    isoalpha3countrycode = models.CharField(max_length=100)
    sector = models.CharField(max_length=100,null=True, blank=True)
    industry = models.CharField(max_length=100,null=True, blank=True)
    description = models.TextField()
    currency_code = models.CharField(max_length=100)
    year1ForwardEPSEstimateAmount = models.FloatField()
    year1ForwardEPSEstimateCurrency = models.IntegerField(default=1)
    year2ForwardEPSEstimateAmount = models.FloatField()
    year2ForwardEPSEstimateCurrency = models.IntegerField(default=1)
    instrument_id = models.IntegerField(default=1)
    short_interest = models.IntegerField(default=1)
    volume = models.IntegerField(default=1)
    shares_outstanding = models.IntegerField(default=1)
    average_volume = models.IntegerField(default=1)
    pricetoearningsratio = models.FloatField()
    returnonequity = models.IntegerField(default=0)
    lasttradedate = models.DateTimeField()
    exdivdate  = models.DateTimeField()
    divpaydate = models.DateTimeField()
    change_amount = models.FloatField()
    change_currency = models.IntegerField(default=1)
    closepriceamount = models.FloatField()
    closepricecurrency = models.IntegerField(default=1)
    currentpriceamount = models.FloatField()
    currentpricecurrency = models.IntegerField(default=1)
    openpriceamount = models.FloatField()
    openpricecurrency = models.IntegerField(default=1)
    marketcapamount = models.FloatField()
    marketcapcurrency = models.IntegerField(default=1)
    marketcapchangeamount = models.FloatField()
    marketcapchangecurrency = models.IntegerField(default=1)
    earningspershareamount = models.FloatField()
    earningspersharecurrency = models.IntegerField(default=1)
    percent_change = models.FloatField()
    fiftytwoweek_minimumamount = models.FloatField()
    fiftytwoweek_minimumcurrency = models.IntegerField(default=1)
    fiftytwoweek_maximumamount = models.FloatField()
    fiftytwoweek_maximumcurrency = models.IntegerField(default=1)
    dailyrange_minimumamount = models.FloatField()
    dailyrange_minimumcurrency = models.IntegerField(default=1)
    dailyrange_maximumamount = models.FloatField()
    dailyrange_maximumcurrency = models.IntegerField(default=1)
    annual_dividendamount = models.IntegerField(default=1)
    annual_dividendcurrency = models.IntegerField(default=1)
    dividend_yield = models.FloatField()
    percentofsharestraded = models.FloatField()
    asset_class = models.IntegerField(default=1)
    chart_url = models.CharField(max_length=100,null=True, blank=True)
    isrealtime = models.BooleanField(default=False)
    bid_amount =  models.FloatField()
    bid_currency = models.IntegerField(default=1)
    ask_amount =  models.FloatField()
    ask_currency = models.IntegerField(default=1)
    ask_yield = models.IntegerField(default=1)
    bid_yield = models.IntegerField(default=1)
    maturity_date = models.DateTimeField()
    open_yield = models.IntegerField(default=1)
    previous_yield = models.IntegerField(default=1)
    open_interest = models.IntegerField(default=0)
    seo_name = models.CharField(max_length=100,null=True, blank=True)
    idc_mdgid = models.IntegerField(null=True)
    website = models.CharField(max_length=100,null=True, blank=True)
    beta3y = models.FloatField()
    home_countrycode = models.CharField(max_length=100,null=True, blank=True)
    gross_margin =  models.FloatField()
    revenue_growth = models.FloatField()

mysite/articles/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('body',)

mysite/articles/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from django.core import serializers
from .forms import CommentForm
from .models import Article, Quote, Comment, Author, Instrument
import itertools
import json
from django.db.models import Q


def home(request):
    qs1 = Article.objects.filter(tags__slug ="10-promise")[:1]
    # i know that .order_by('?') can be heavy on larger datasets, but its fine for this small project
    qs2 = Article.objects.all().order_by('?').exclude(pk=qs1)[:3]
    latest_article_list = itertools.chain(qs1, qs2)
    context = {'latest_article_list': latest_article_list}
    return render(request, 'articles/home.html', context)


def article(request, article_uuid):
    article = get_object_or_404(Article, pk=article_uuid)
    comments = article.comments.order_by('-created')[:10] # set a reasonable amount and have the newest at the top
    suggested_articles = Article.objects.all()[:3]
    insturments = article.insturments.all()
    symbolset = set(instrument.symbol for instrument in insturments)
    companyset = set(instrument.company_name for instrument in insturments)
    stock_list = json.dumps([{
        'company_name': quote.company_name,
        'symbol': quote.symbol,
        'exchange_name': quote.exchange_name,
        'currentpriceamount': quote.currentpriceamount,
        'changeamount': quote.change_amount,
        'changepercent': quote.percent_change
    } for quote in Quote.objects.filter(Q(symbol__in= symbolset) | Q(company_name__in= companyset)) ])
    # the code above will grab only the relevant Stocks to this article, with the symbol
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.article = article
            comment.save()
            context = {'article': article, 'suggested_articles': suggested_articles, 'stock_list': stock_list,'comments': comments, 'form': form}
            return render(request, 'articles/article.html', context )
    else:
        form = CommentForm()
        context = {'article': article, 'suggested_articles': suggested_articles, 'stock_list': stock_list, 'comments': comments, 'form': form}
    return render(request, 'articles/article.html', context)


def stocks(request):
    stocks = Quote.objects.all()
    context = {'stocks': stocks}
    return render(request, 'articles/stocks.html', context)

def authors(request):
    authors = Author.objects.all()
    context = {'authors': authors}
    return render(request, 'articles/authors.html', context)


def author(request, author_uuid):
    author = get_object_or_404(Author, pk=author_uuid)
    recent_article = author.authors.order_by('-publish_at')[:1]
    print(author)
    context = {'author': author, 'recent_article': recent_article}
    return render(request, 'articles/author.html', context)

mysite/articles/templates/articles/article.html
{% extends "articles/base.html" %}

{% block content %}
<div class="container article-content-inner">
    <div class="row">
        <div class="col-sm-12">
            <div class="article-header">
                <header>
                    <div id="adv_text" class="adv-heading"></div>
                    <h1>Tesla Unveils 2 Mind-Blowing New Vehicles -- What You Need to Know</h1>
                    <!--<h2>You won't believe the specs on these new all-electric vehicles. </h2>-->
                </header>
            </div>
        </div>
    </div>
    <div class="row">
        <main class="col-sm-7 col-md-8">
            <div class="author-tagline author-inline">
                <div class="author-and-date">
                    <div class="author-byline">
                      {% for author in article.authors.all %}
                      <div class="author-name"> {{author.first_name}} {{author.last_name}} </div>
                      <div class="author-username">
                          (<a href="{% url 'articles:author' author.uuid %}"> {{author.username}}</a>)
                      </div>
                      {% endfor %}
                    </div>
                    <div class="article-pub-date">
                        <div class="publication-date">
                            {{article.publish_at}}
                        </div>
                    </div>
                </div>
            </div>
            <section class="article-body">
                <div class="article-content">
                  {{article.body |safe }}
                </div>
                <div class="article-disclosure">
                    <p>{{article.disclosure | safe}}</p>
                </div>
                <div class="special-message">
                    <h5>{{article.byline}}</h5>
                    {% for author in article.authors.all %}
                      <p>{{ author.short_bio | safe }}</p>
                    {% endfor %}
                </div>
            </section>

            <button class="btn" id="showcomment" >Add Comment</button>
            <div id="formarea">
              <h1>New comment</h1>
            <form method="POST" class="post-form">{% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Send</button>
            </form>
          </div>
            <hr>
            <ul class="list-group">
            {% for comment in comments %}
              <li class="list-group-item comment"><div class="commentdiv">
                  <div class="date">{{ comment.created }}</div>
                  <p>{{ comment.body|linebreaks }}</p>
              </div></li>
            {% empty %}
            </ul>
                <p>No comments here yet :(</p>
            {% endfor %}
        </main>
        <aside class="col-sm-5 col-md-4 p-l">
            <section class="related-tickers">
              <div class="block-title">
                  <hr><h2>Stocks<button class="btn" id="refreshstocks" > New Stocks</button>
                   </h2>
              </div>
              <div class="ticker-row" id="ticker-row">
                <!--  This id added via javascript-->
                  </div>
            </section>
            <section class="read-more-section">
                <div class="block-title">
                    <hr><h2>Read More
                    <button type="button" class="btn btn-secondary" data-container="body" data-toggle="popover" data-placement="top" data-content="Find more exciting articles at https://www.fool.com/">
                      <i class="fas fa-info-circle"></i>
                    </button>
                </h2></div>
                <ul class="two-line-list">
                  {% for article in suggested_articles %}
                    <li><a  href="{% url 'articles:article' article.uuid %}">{{ article.headline }}</a></li>
                  {% endfor %}
                </ul>
            </section>
        </aside>
    </div>
</div>
{% endblock %}

mysite/articles/templates/articles/author.html
{% extends "articles/base.html" %}

{% block content %}
<div class="container content-inner">
    <div class="main-col">
      <div class="card mb-3" >
          <div class="row no-gutters">
            <div class="col-md-4">
                  <img class="card-img" src="{{ author.large_avatar_url}}" alt="">
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h3 class="card-title">{{author.first_name}} {{author.last_name}}</h3>
                {% for article in recent_article %}
                <h6 class="card-text  mb-2">Recent Article: <a href="{% url 'articles:article' article.uuid %}">{{article.headline}}</a></h6>
                {% endfor %}
                <p class="card-text">{{author.long_bio | safe}}</p>
              </div>
            </div>
          </div>
        </div>
    </div>

</div>
{% endblock %}

mysite/articles/templates/articles/authors.html
{% extends "articles/base.html" %}

{% block content %}
<div class="container article-content-inner">

  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Username</th>
        <th scope="col">Email</th>
      </tr>
    </thead>
    <tbody>
      {% for author in authors %}
      <tr>
        <th scope="row"><a href="{% url 'articles:author' author.uuid %}"> {{author.first_name}} {{author.last_name}}</a></th>
        <td>{{author.username}}</td>
        <td>{{author.email}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

mysite/articles/templates/articles/base.html
{% load static %}

<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>html</title>

        <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

        <link rel="stylesheet" href="{% static 'css/global.css' %}">

    </head>
    <body>
      <div class="container top-bar">
        <nav class="navbar navbar-expand-lg navbar-light">
          <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'articles:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'articles:stocks' %}">Stocks</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'articles:authors' %}">Authors</a>
            </li>
          </ul>
        </div>
         </nav>
       </div>

        {% block content %}{% endblock %}
    </body>
</html>
<script src="https://kit.fontawesome.com/ef018246f5.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script>
var stockstodisplay = []
var a = "{{stock_list}}";
var ticker = document.getElementById('ticker-row')


$(function () {
  $('[data-toggle="popover"]').popover()
})

if(a.length > 0){
    var stocks = JSON.parse('{{ stock_list | safe }}');
    console.log(stocks.length)
    if(stocks.length < 4){
      document.getElementById("refreshstocks").style.display = "none";
    }
    random_stocks(stocks);
    add_stocks(stockstodisplay)

    document.getElementById("refreshstocks").onclick = function() {
        document.getElementById('ticker-row').innerHTML = "";
        stockstodisplay = []
        random_stocks(stocks);
        add_stocks(stockstodisplay)
    }
    document.getElementById("formarea").style.display = "none";
    document.getElementById("showcomment").onclick = function() {
        document.getElementById("formarea").style.display = "";
        document.getElementById("showcomment").style.display = "none";
  }
}


// This function is for prevent lap over that the original random did
function shuffle(a) {
    for (let i = a.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [a[i], a[j]] = [a[j], a[i]];
    }
    return a;
}

function add_stocks(items){
  for (i = 0; i < items.length; i++) {
    ticker.innerHTML += '<div class="list-group list-group-flush"><div href="#" class="list-group-item"><div class="d-flex w-100 justify-content-between"><h5 class="mb-1">' + items[i].company_name + '</h5><small>Current Price: $' + items[i].currentpriceamount + '</small></div><p class="mb-1 exchange">' + items[i].exchange_name +':'+ items[i].symbol +'</p><small>Price Change Amount: $'+ items[i].changeamount + '</small><small>Price Change Percentage: ('+ items[i].changepercent + '%)</small><div></div>'
  }
}

function random_stocks(items){
  items = shuffle(items)
  if(items.length < 3){
    for (i = 0; i < items.length; i++) {
      stockstodisplay.push(items[i])
    }
  }else{
    for (i = 0; i < 3; i++) {
      stockstodisplay.push(items[i])
    }
  }
  }

</script>

mysite/articles/templates/articles/home.html
{% extends "articles/base.html" %}

{% block content %}
<div class="container content-inner">
  <div class="card-deck">

  {% if latest_article_list %}
      {% for article in latest_article_list %}
        {% if forloop.first %}
    <div class="main-col">
      <div class="card mb-3" >
          <div class="row no-gutters">
            <div class="col-md-4">
              <a href="{% url 'articles:article' article.uuid %}">
                {% for image in article.images.all %}
                  {% if forloop.first %}
                  <img class="card-img" src="{{ image.url}}" alt="">
                    {% endif %}
                  {% endfor %}
              </a>
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h3 class="card-title"><a href="{% url 'articles:article' article.uuid %}">{{ article.headline }}</a></h3>
                <h6 class="card-text  mb-2">{{article.byline}}| {{article.created}}</h6>
                <p class="card-text">{{article.promo}}</p>
              </div>
            </div>
          </div>
        </div>
    </div>
    {% else %}
    <div class="card" style="width: 18rem;">
      <a  href="{% url 'articles:article' article.uuid %}">
        {% for image in article.images.all %}
          {% if forloop.first %}
          <img style="height: 15rem " class="card-img-top" src="{{ image.url}}" alt="">
            {% endif %}
          {% endfor %}
      </a>
      <div class="card-body">
        <h5 class="card-title"><a  href="{% url 'articles:article' article.uuid %}">{{ article.headline }}</a></h5>
        <h6 class="card-subtitle mb-2">{{article.byline}}| {{article.created}}</h6>
        <p class="card-text">{{article.promo}}</p>
      </div>
    </div>
      {% endif %}
    {% endfor %}
{% endif %}
</div>
</div>
{% endblock %}

mysite/articles/templates/articles/stocks.html
{% extends "articles/base.html" %}

{% block content %}
<div class="container article-content-inner">

  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Company Name</th>
        <th scope="col">Symbol</th>
        <th scope="col">Sector</th>
        <th scope="col">Industry</th>
        <th scope="col">Website</th>
        <th scope="col">Revenue growth</th>
      </tr>
    </thead>
    <tbody>
      {% for stock in stocks %}
      <tr>
        <th scope="row"> {{stock.company_name}}</th>
        <td>{{stock.symbol}}</td>
        <td>{{stock.sector}}</td>
        <td>{{stock.industry}}</td>
        <td>{{stock.website}}</td>
        <td>{{stock.revenue_growth}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}